"""Add knowledge_base_version to chatbots

Revision ID: 51f81e665f90
Revises: 20260607_p3
Create Date: 2026-06-08 10:15:48.749328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '51f81e665f90'
down_revision: Union[str, Sequence[str], None] = '20260607_p3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_caches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_base_version', sa.Integer(), nullable=False),
    sa.Column('persona_version', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'chatbot_id', 'query_hash', 'knowledge_base_version', 'persona_version', name='uq_semantic_cache_query')
    )
    op.create_index('idx_semantic_cache_active', 'semantic_caches', ['chatbot_id', 'is_active', 'expires_at'], unique=False)
    op.drop_index(op.f('idx_api_keys_prefix'), table_name='api_keys')
    op.drop_constraint(op.f('uq_api_keys_prefix'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=True)
    op.add_column('chatbots', sa.Column('knowledge_base_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('personas', sa.Column('persona_version', sa.Integer(), nullable=False, server_default='1'))
    op.drop_index(op.f('idx_subscriptions_org_active'), table_name='subscriptions', postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_subscriptions_org_active'), 'subscriptions', ['org_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.drop_column('personas', 'persona_version')
    op.create_index(op.f('ix_knowledge_chunks_text_search_vector'), 'knowledge_chunks', ['text_search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('chatbots', 'knowledge_base_version')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.create_unique_constraint(op.f('uq_api_keys_prefix'), 'api_keys', ['key_prefix'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_api_keys_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.drop_index('idx_semantic_cache_active', table_name='semantic_caches')
    op.drop_table('semantic_caches')
    # ### end Alembic commands ###
