"""add_retry_after_to_knowledge_job

Revision ID: ad20ca5a8485
Revises: 20260525_builder
Create Date: 2026-05-31 13:30:21.266087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad20ca5a8485'
down_revision: Union[str, Sequence[str], None] = '20260525_builder'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.get_bind().begin_nested():
            op.add_column('knowledge_jobs', sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True))
    except Exception:
        pass
    try:
        with op.get_bind().begin_nested():
            op.drop_index(op.f('idx_subscriptions_org_active'), table_name='subscriptions', postgresql_where="((status)::text = 'active'::text)")
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_subscriptions_org_active'), 'subscriptions', ['org_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.drop_column('knowledge_jobs', 'retry_after')
    # ### end Alembic commands ###
